export enum TableNameEnum {
  REFRESH_TOKENS = 'refresh_tokens',
  USERS = 'users',
  FURNITURE = 'furniture',
  ORDER = 'order',
  ORDER_FURNITURE = 'order_furniture',
  CATEGORY_FURNITURE = 'category_furniture',
  SUB_CATEGORY_FURNITURE = 'subcategory_furniture',
  BRAND = 'brand',
  SITE_STATISTIC = 'site_statistic',
  FURNITURE_STATISTIC = 'furniture_statistic',
  CALCULATE_RATE_FURNITURE = 'calculate_rate_furniture',
  SHIPPING_INFO = 'shipping_info',
  PAYMENT_INFO = 'payment_info',
  BANNER = 'banner',
  COLOR = 'color',
  MATERIAL = 'material',
  SIZE = 'size',
}
