export enum TableNameEnum {
  REFRESH_TOKENS = 'refresh_tokens',
  IS_SHOW_PRICE = 'is_show_price',
  DELIVERY = 'delivery',
  USERS = 'users',
  FURNITURE = 'furniture',
  ORDER = 'order',
  QUANTITY_FURNITURE_IN_ORDER = 'quantity_furniture_in_order',
  CATEGORY_FURNITURE = 'category_furniture',
  SUB_CATEGORY_FURNITURE = 'subcategory_furniture',
  BRAND = 'brand',
  CUSTOMER_INFO = 'customer_info',
  FURNITURE_STATISTIC = 'furniture_statistic',
  CALCULATE_RATE_FURNITURE = 'calculate_rate_furniture',
  SHIPPING_INFO = 'shipping_info',
  PAYMENT_INFO = 'payment_info',
  BANNER = 'banner',
  COLOR = 'color',
  MATERIAL = 'material',
  SIZE = 'size',
}
