export enum UserEnum {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  REGISTERED_CLIENT = 'REGISTERED_CLIENT',
  UNREGISTERED_CLIENT = 'UNREGISTERED_CLIENT',
  OAUTHREGISTERED_CLIENT = 'OAUTHREGISTERED_CLIENT',
}
