export enum UserEnum {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  REGISTERED_CLIENT = 'REGISTERED_CLIENT',
  UNREGISTERED_CLIENT = 'UNREGISTERED_CLIENT',
  EXTERNAL_SELLER = 'EXTERNAL_SELLER', // todo. i don't know use or no
}
